### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by PeGaSuS-Coder**
Let's add a `Go back` button for easiness :)

### CODE REVIEW

**Comment by Rouji** [comment]
Why? Browsers already have one

**Comment by PeGaSuS-Coder** [comment]
My main reason is that when you use the browser `go back` arrow the upload field is still filled with the last uploaded file.

That's the only advantage I have against the browser `go back` arrow.

**Comment by Rouji** [comment]
How/why is that a problem?

**Comment by PeGaSuS-Coder** [comment]
It isn't a problem per se.
I just think that a blank upload field looks better.
Feel free to close it if there's no usefulness.

Cheers

**Comment by Rouji** [comment]
Yeah sorry, but I don't really see too much benefit in this. People don't re-upload the same file all the time, so it doesn't seem to be a problem.

**Pull request closed without merging**
